name: Build

on:
  workflow_dispatch:

jobs:
  build_project:
    name: build c files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: Build our Project
      run: bash compile.sh

    - name: Commit build
      run: |
          git config --global user.name 'Silas Wrinker'
          git config --global user.email 'alcosojr79@gmail.com'
          git commit -m "Built project"
          git push


