name: Build

on:
  workflow_dispatch:

jobs:
  build_project:
    name: build c files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: Build our Project
      run: gcc main.c users.c -o sand.c 
